import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import profilePic from "../../public/images/profile/developer-pic-1.png";

import Layout from "../components/Layout";
import AnimatedText from "../components/AnimatedText";
import { LinkArrow } from "../components/Icons";
import HireMe from "../components/HireMe";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <div className="flex items-center justify-center w-full mb-10 ">
            <Image
              src={profilePic}
              alt="Picture of the author"
              width={500}
              height={500}
              className="rounded-full"
            />
          </div>
        </Layout>
      </main>
    </>
  );
}
