import Head from "next/head";
import Layout from "../components/Layout";
import { getAllPosts } from "../../lib/notionAPI";

export const getStaticProps = async () => {
  const allPost = await getAllPosts();

  return {
    props: {
      allPost,
    },

    revalidate: 60,
  };
};

export default function Home() {
  console.log("allPost", allPost);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <div className="flex items-center justify-center w-full mb-10 "></div>
        </Layout>
      </main>
    </>
  );
}
